---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: email-secret
spec:
  encryptedData:
    password: AgARMBg5TaFi4FvMLsQvWN5Lcigp4sWdjZ0U0chbczF7KeKI6fFaXPI14YmX4praeMLBcbZlghhawVIQvsi3W/L8w6FxFeCCzBP3fla3cP2PlM8yvGj6AIa1aaxbDg4JbBPbls0shOWMSaHUrI9oahc4a1YBxvPSPozi3XZjc/9vko3ob3hPCzY6VzuwHqcHoO+pU+7Gsc54xeKvG0TIing8r9mctE+4i9K5wXiLuSsig8jWgKS5vQifQgZXHJZHblN4s/OhimRY5JudHp7iKZe9JDx2u4OB1kYxfX1Mtl75dswJopFNTmIArc89WadDzAM7osWWk9hMUxloy8qXGZwdb9hOsthWa8jkF5VdznHWBoNNs06y8PkOEbPvIfrqkDLdm+nI8JlSBEPIExi2omSZD4cKUWwK8IqTxv7CAMTUkCFFUFb+FhJX+SxUhicZ3JQCXTLC5SnIWGMitNSgQjefYtJ+Exm0T5pSEBWfzWaVmJei8FujRI6K/GLRJ0Y+fX2aNLScrpNGL/48z0O+7ea2rv+9viiQYRkF212uwpwJpwCFN16bOpM2Y0ibuEbZ3dAcJzcYOFg/wxC8P/0/c/5Wka8gcbP2Iwacj0vVcAnX8IZSaWa5OZWYh5SW+JvTe2k84oh7AfrZf0H71OK93C7pDSqvRst60394bBgRD3GHI9hAqisRRFGLTe5A1VTsmeu0jE6nVk2DM040nkrjrZd0t5sptQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: email-secret
    type: Opaque
