apiVersion: v1
kind: ServiceAccount
metadata:
  name: application-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-manager
rules:
- apiGroups: ["apps", "", "request.jaypd.github.com"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: application-deployment-binding
subjects:
- kind: ServiceAccount
  name: application-sa
roleRef:
  kind: Role
  name: deployment-manager
  apiGroup: rbac.authorization.k8s.io