# permissions for end users to view userrequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: trial-custom
    app.kubernetes.io/managed-by: kustomize
  name: userrequest-viewer-role
rules:
- apiGroups:
  - request.jaypd.github.com
  resources:
  - userrequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - request.jaypd.github.com
  resources:
  - userrequests/status
  verbs:
  - get
